<?php
/**
 * @file
 * Hooks implementations.
 */

/**
 * Add the basepath to the Drupal.settings js object.
 *
 * @param $page
 *    Page array
 */
function ckeditor_responsive_plugin_page_build(&$page) {
  global $base_path;
  global $base_url;

  $module_base_path = $base_url . $base_path . drupal_get_path('module', 'ckeditor_responsive_plugin');

  $my_settings = array(
    'basePath' => $module_base_path,
  );
  drupal_add_js(array('ckeditor_responsive_plugin' => $my_settings), 'setting');
}

/**
 * Define the CKEditor plugin.
 *
 * @return array
 *   CKEditor settings
 */
function ckeditor_responsive_plugin_ckeditor_plugin() {
  return array(
    'responsivness' => array(
      'name' => 'responsivness',
      'desc' => t('CKEditor Responsive Plugin : Allow to insert responsive areas'),
      'path' => drupal_get_path('module', 'ckeditor_responsive_plugin') . '/responsivness/',
      'buttons' => array(
        'responsivness' => array(
          'icon' => 'images/responsivness.png',
          'label' => t('Add responsive area'),
        ),
      ),
      'default' => 't',
    ),
  );
}

/**
 * Extend CKEditor's settings.
 *
 * @param Array $settings
 *   CKEditor base settings
 * @param Array $conf
 *   CKEditor configuration
 */
function ckeditor_responsive_plugin_ckeditor_settings_alter(&$settings, $conf) {
  if (isset($settings['js_conf']['extraAllowedContent'])) {
    $settings['js_conf']['extraAllowedContent'] .= "'div(*);'";
  }
  else {
    $settings['js_conf']['extraAllowedContent'] = "'div(*);'";
  }
}
