<?php
/**
 * @file
 * Hooks implementations.
 */

/**
 * Add the basepath to the Drupal.settings js object.
 * Implements hook_page_build().
 *
 * @param array $page
 *    Page array.
 */
function ckeditor_responsive_plugin_page_build(array &$page) {
  global $base_path;
  global $base_url;

  $module_base_path = $base_url . $base_path . drupal_get_path('module', 'ckeditor_responsive_plugin');

  $my_settings = array(
    'basePath' => $module_base_path,
  );
  drupal_add_js(array('ckeditor_responsive_plugin' => $my_settings), 'setting');
}

/**
 * Extend CKEditor's settings.
 * Implements hook_ckeditor_settings_alter().
 *
 * @param array $settings
 *   CKEditor base settings.
 * @param array $conf
 *   CKEditor configuration.
 */
function ckeditor_responsive_plugin_ckeditor_settings_alter(array &$settings, array $conf) {
  if (isset($settings['js_conf']['extraAllowedContent'])) {
    $settings['js_conf']['extraAllowedContent'] .= "'div(*);'";
  }
  else {
    $settings['js_conf']['extraAllowedContent'] = "'div(*);'";
  }
}
