<?php


/**
 * @todo activation du plugin pour l'ensemble des profile ckeditor
 */
function ckeditor_responsive_plugin_install() {

}

/**
 * @todo activer l'option allowExtraTags
 */
function ckeditor_responsive_plugin_enable() {

}

/**
 * @todo désactiver l'option allowExtraTags
 */
function ckeditor_responsive_plugin_disable() {

}

/**
 * @todo désactivation du plugin pour l'ensemble des profile ckeditor
 */
function ckeditor_responsive_plugin_uninstall() {

}